spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security-demo?characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  redis:
    password: 123456


server:
  port: 8088

com:
  imooc:
    security:
#      browser:
#        signUpUrl: "/demo-signUp.html"
       code:
         image:
           length: 4
           urls: /user,/user/*
       social:
         qq:
           appId: aa
           appSecret: bb
